name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -f MicroServiceAPIOne/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/microserviceone:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/microserviceone:${{ github.sha }}
